spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
jdbc:
  mysql:
    datasource:
      url: jdbc:mysql://localhost:5306/db
      username: midasit
      password: mid@sit
  h2:
    console:
      enabled: false