version: '3.3'
services:
  tgc_db:
    image: mariadb:10
    container_name: tgc_db
    ports:
      - 5306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always